[package]
name = "patchouli-tauri"
version = "0.1.0"
description = "Patchouli, the Unmoving Great Library"
authors = ["Patchouli contributors"]
edition = "2021"

[lib]
name = "patchouli_tauri"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
patchouli-opac-api = { path = "../src-opac" }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
tauri = { version = "2", features = [] }

[profile.release]
strip = "symbols"
lto = "thin"
codegen-units = 1
panic = "abort"
